remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
deploy:
    type: git
    repo: git@github.com:secondtonone1/Zenfish-zy.github.io.git  #这里的网址填你自己的
    branch: main

